travis:
  secure:
    BINSTAR_TOKEN: lDAChhAHX1l4BAO71IoP8n3j56gcp/tMeas3kXJijEXyHrw7FENR0maQyZMR79vhwGsrrwY8b9w/kjd2KtRWT8hnyzg6OSzT92hLEtX4uKSLYCkMtHX8qtv2zDxeqnyMKMcZtQsfGDE/9rRkT9l49s/7qiHOHDpeyrZgnlQeMoTZe7VbY6K5C+/PtgPrnRVul3CQrl6cj1RxkRo+25Krx9uu/AOXp39qRQTX4T7H662C6b8F66Kio5M5px8o5kVuXJxi35/El5pz58tWBDaq1wD999JFFc+uZwymPzOnNQVYqZG4mwXoCevOcnIUW/8NXR7fsWD+kv3qrPsPorGPsR2NuK9g+X533HP4JZ3aH6o2MJu2hE/3nPJ+lxGIncpUxAkBbVthzKonSSYJ3IbupB9b79DQzf2tf5+Xdj0LBwacaSiHyQ9OUHnTeMLfyiuKwdhUIET8+QP5tlj67LgGOOv3CEPxP7vduIxhLqIZdpbrYd1l8nlnQ3mX+I+8fLQfrQbX26ACk0ozNkTkrpTVEOLn9v5W9WA1o1O+A2juF3c3UCurTaOF5rQZ4cCuRxaOguBF74UNDraGWdWvsj+sBvvLEEl/J+TleJ6qqBdjbkWdoHqdUmlG/+gD4Wmmp9okS7j8lfeiagkk40BaHkzLFdJ3XgDIkySWCSAPl8BTbvo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
