travis:
  secure:
    BINSTAR_TOKEN: YfgntugMZYtcCCPcLaFUVBDGZ3YDJVqVPprLApPw9JIqktkAOkSF20cw9sNx9uOQEKabb9T+QGmkcQXqBNR2T3VjAAo8IGhMbBghe1j4D3FldJo5fiBttZrd/wHlBZJMYjoBIxQoBqpqOT58XRYOls3ijBc1flWOmXkzcz0T0RFu9JH18MvJx9l/0psrUXQBj9D59tSEGBnZwEA1bLCij+EU0U0L23XFoqlL+qqb2xRqFhu22Hs412o++wvA/d+pKRs+H/h59VRFaJXjE1LmbTRz+HVYJvaFpYdibqTlhQLcWrxRp9CFO9/RrjnmIDXjxycHmYpeJ53aBYIPZJv5uoQS3N8guS1QrXoAHGYixjTsaC31+M6r1dfc8vTyWOE5XoUogVFaNOkxmV2/KQwIhDCNmaSHrj+VSKU9L41m5wdcO8ce/Fs4TBKEQjbXzpS5DZIqOgLjVoNxDK39MkOT/ms7oMPtklg0kMozUAx/tnar8PyhkLx3zf03DROct4FIBj+AAKkmbs94dMdLwtf+WKx0zQttbQmp0xnfqfJPlB4bOYsN0Xh5TDo4VfAvcIFZ1Lcr4ll5Xfw+Bqonx4+hc3IDVjKB1/PRi1/2j8fMLODfzfaA3WNDGhI9dPeAuretLu45SzqsjxoTay09LvQFPJYn2cgdKmLDHl1MfrhQHuU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
